<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceDesignerFiles>false</GenerateResourceDesignerFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.Net.Demo" Version="2026.2.1" />
    <PackageReference Include="Zeus.Net.NFe.NFCe" Version="2025.8.12.1032" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="NFCe\Fontes\**\*.*" />
  </ItemGroup>

</Project>
