<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceDesignerFiles>false</GenerateResourceDesignerFiles>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fontes\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
    <PackageReference Include="Zeus.Net.NFe.NFCe" Version="2026.8.18.2047" />
  </ItemGroup>
</Project>
