trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: windows-latest

steps:
  - task: UseDotNet@2
    inputs:
      version: "10.0.x"

  - script: dotnet restore Loja.sln
    displayName: Restore

  - script: dotnet build Loja.sln -c Release --no-restore /warnaserror
    displayName: Build
