<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="zxing">
      <HintPath>Dlls\zxing.dll</HintPath>
    </Reference>
    <Reference Include="zxing.presentation">
      <HintPath>Dlls\zxing.presentation.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Dlls\*.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphicsPrinter\GraphicsPrinter.csproj" />
    <ProjectReference Include="..\NFe.Danfe.Base\NFe.Danfe.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Zeus.Net.NFe.NFCe" Version="2026.5.5.1505" />
  </ItemGroup>
</Project>
